Feature/lesson 7
pavelryzhikov/home-work pull request #7
Opened 2021-11-21 19:35 UTC by pavelryzhikov

2021-11-24 21:30 UTC, Upforup requested changes

2021-11-24 21:30 UTC, Upforup commented on src/main/java/com/github/pavelryzhikov/dto/Account.java
> +      if (o.getId() == null) {
Если значения полей null недопустимы то лучше проверять это при создании объекта

2021-11-24 21:30 UTC, Upforup commented on src/main/java/com/github/pavelryzhikov/utils/AccountUtils.java
> +        accounts.sort(Account::compareTo);
В задании предлагается реализовать сортировку тремя разными способами. Это возможно сделать через Comparator. Например так можно реализовать первое требование:         accounts.sort(new Comparator<Account>() {
            @Override
            public int compare(Account o1, Account o2) {
                return Long.compare(o1.getId(), o2.getId());
            }
        });

2021-11-24 21:30 UTC, Upforup commented on src/test/java/com/github/pavelryzhikov/utils/AccountUtilsTest.java
> +            add(Account.builder().id(1L).createDate(LocalDate.now().minusDays(4)).balance(BigDecimal.TEN).build());
Это не очень хороший способ инициализации списка. 
       List\<Account\> accounts = new ArrayList<>();
        Collections.addAll(accounts,
                Account.builder().id(1L).createDate(LocalDate.now().minusDays(4)).balance(BigDecimal.TEN).build(),
Account.builder().id(null).createDate(LocalDate.now().minusDays(3)).balance(BigDecimal.TEN.subtract(BigDecimal.ONE)).build());

2021-11-28 22:24 UTC, RodinDenis approved these changes

2021-11-28 22:24 UTC, RodinDenis commented on src/main/java/com/github/pavelryzhikov/dto/Account.java
> +   Long id;
Зачем использован класс обертка? Лучше везде где допустимо стараться использовать long. Только там где действительно без ссылочного типа не обойтись стоит прибегать к классам оберткам

2021-12-06 20:25 UTC, pavelryzhikov commented on src/main/java/com/github/pavelryzhikov/dto/Account.java
> +      if (o.getId() == null) {
как правильно в описании объекта дать понять что поле может иметь null?
или это считается по умолчанию?

2021-12-06 20:26 UTC, pavelryzhikov commented on src/main/java/com/github/pavelryzhikov/dto/Account.java
> +      if (o.getId() == null) {
> 

как правильно в описании объекта дать понять что поле может иметь null?
или это считается по умолчанию?

2021-12-19 13:41 UTC, Upforup approved these changes
ОК. Незначительные замечания.

2021-12-19 13:41 UTC, Upforup commented on src/main/java/com/github/pavelryzhikov/Main.java
> +        List list = new ArrayList();
некорректное использование generic коллекции, следует указывать тип элементов.

2021-12-19 13:41 UTC, Upforup commented on src/test/java/com/github/pavelryzhikov/repository/AccountRepositoryImplTest.java
> +        List<String> strings = new ArrayList<String>() {{
создание коллекций с использованием {{}} является плохой практикой

2021-12-19 13:43 UTC, Upforup commented on src/main/java/com/github/pavelryzhikov/dto/Account.java
> +      if (o.getId() == null) {
Документация поможет помочь в понимании, что поле может быть null. Так же возможно использование специальных аннотаций.

2022-01-11 18:03 UTC, merged